server:
  port: 8090
spring:
  data:
    mongodb:
      username: houdaelhirm
      password: 7RiZRnQZYmJOKt7u
      host: localhost
      port: 27018
      database: user
      authentication-database: admin

application:
  config:
    product-url: http://localhost:8222/api/v1/product
    payments-url: http://localhost:8222/api/v1/payments

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka